[ULMS-1742] Set up authentication via JWT tokens
foxford/presence pull request #4
Opened 2022-02-15 10:19 UTC by mgrachev

2022-02-21 09:04 UTC, khodzha requested changes

2022-02-21 09:04 UTC, khodzha commented on src/app/ws/handler.rs
> +            _ = auth_timeout_interval.tick(), if !authenticated => {
i feel like everything authentication related should be moved out of this loop since you only need to do authn and authn timeout once and forget about that
something like:
```rust

let maybe_authn_msg = tokio::time::timeout(receiver.next()).await?;
if check_authn(maybe_authn_msg).is_err() {
  socket_close();
}

// authn done, and we never need to bother down here
// just keep pinging
loop {
    tokio::select! {
        m = receiver.next() => {
            if ping_sent && m.is_pong() {
                ping_sent = false;
            }
        }
        _ = ping_interval.tick() => {
            send_ping().await;
            ping_sent = true;
            pong_interval.reset();
        }
        _ = pong_interval.tick() => {
            if ping_sent {
                error!("failed to await pong failed")
                break;
            }
        }
    }
}
```


that would be much simpler

2022-02-21 09:10 UTC, khodzha commented on migrations/20220204101411_create_table_session.sql
> +    );
index by classroom_id will be useful too for future queries

also consider adding unique index on (classroom_id, agent_id (, and maybe replica_id?)) since there can be only one agent in classroom

2022-02-22 15:04 UTC, manifest commented on src/app/ws/handler.rs
> +fn handle_message(message: Message, authn: Arc<ConfigMap>) -> Result<String, String> {
or some other error type extending `authn::Error`

2022-02-22 16:22 UTC, mgrachev commented on src/app/ws/handler.rs
> +                Err(_) => Err(make_response(ConnectFailure::Unauthenticated.into())),
What do you mean? What should I change here?

2022-02-22 16:30 UTC, mgrachev commented on src/app/ws/handler.rs
> +fn handle_message(message: Message, authn: Arc<ConfigMap>) -> Result<String, String> {
We have `enum ConnectFailure` and maybe it's a good option to return from this function?
I don't quite understand how `authn::Error` can help us, because we have to return a serialized JSON object to the clients.

2022-02-22 16:53 UTC, mgrachev commented on src/app/ws/handler.rs
> +            Ok(msg) => match handle_message(msg, authn) {
I plan to do it in the next task.

2022-02-24 16:21 UTC, manifest approved these changes

2022-02-28 11:38 UTC, khodzha approved these changes

2022-02-28 11:58 UTC, merged