WIP: Add API for list of agents
foxford/presence pull request #5
Opened 2022-02-24 17:42 UTC by mgrachev

2022-03-01 07:45 UTC, khodzha approved these changes

2022-03-03 07:30 UTC, khodzha requested changes

2022-03-03 07:30 UTC, khodzha commented on src/app/router.rs
> +            get(v1::classroom::list_agents::<AppState>),
we need to add `.options` handler here to handle CORS so clients could do requests for themselves

2022-03-03 07:51 UTC, mgrachev commented on src/app/router.rs
> +            get(v1::classroom::list_agents::<AppState>),
Done.

2022-03-03 08:07 UTC, khodzha commented on src/app/router.rs
> +            get(v1::classroom::list_agents::<AppState>),
you'll need this layer, it adds cors headers
https://github.com/foxford/dispatcher/blob/3b2b36b6090d39af06235995c2264cb5cbbc4c2b/src/app/http.rs#L71

2022-03-03 08:50 UTC, mgrachev commented on src/app/router.rs
> +            get(v1::classroom::list_agents::<AppState>),
Added.

2022-03-11 07:28 UTC, manifest approved these changes

2022-03-11 07:28 UTC, manifest commented on src/db/agent_session.rs
> +                classroom_id = $1::uuid
Do we need a `LIMIT` here?

2022-03-11 07:31 UTC, manifest approved these changes

2022-03-11 08:54 UTC, mgrachev commented on src/db/agent_session.rs
> +                classroom_id = $1::uuid
This needs to be discussed. If necessary, I'll add it in the next PR.

2022-03-11 09:01 UTC, khodzha approved these changes

2022-03-11 09:03 UTC, merged