Save agents session in database
foxford/presence pull request #9
Opened 2022-03-05 14:26 UTC by mgrachev

2022-03-14 18:14 UTC, khodzha requested changes

2022-03-18 12:38 UTC, manifest commented on src/test_helpers/factory/agent_session.rs
> +                COUNT(*) AS total
COUNT(1)

2022-03-18 12:38 UTC, manifest commented on src/test_helpers/factory/agent_session_history.rs
> +                COUNT(*) AS total
COUNT(1)

2022-03-21 07:47 UTC, khodzha approved these changes

2022-03-22 11:05 UTC, closed without merging